### PR TITLE
[SANTUARIO-616] enable manual decryption of the EncryptedKey with KeyAgreement

### PR DESCRIPTION
**Pull request by jrihtarsic**
Recently the KeyAgreement feature incorporating ECDH-ES, X25519, and X448 methods was the introduced to the XMLSEC library. Notably, several software vendors have already developed their own solutions. The objective of this task is to provide an option for bypassing KeyAgreement resolution if the symmetric key has already been supplied to XMLCipher.

See the [SANTUARIO-616](https://issues.apache.org/jira/browse/SANTUARIO-616) for details.

### CODE REVIEW

**Review by coheigea — APPROVED** [review]
LGTM. @seanjmullan please take a look

**Review by coheigea — COMMENTED** [review]
Please resolve the conflicts

**Comment by jrihtarsic** [comment]
The conflicts are resolved now.

**Comment by seanjmullan** [comment]
> LGTM. @seanjmullan please take a look

Sorry been busy with work, etc so the *earliest* I can get to this and other reviews that are pending my review is end of next week sometime.

**Review by seanjmullan — APPROVED** [review]

**Comment by seanjmullan** [comment]
LGTM.

**Pull request merged**
