### PR TITLE
adding RNG specified via system property

### PR DESCRIPTION
**Pull request by isaacjensen**
Should allow ability to specify a JAVA_OPT for RNG alg.

### CODE REVIEW

**Comment by isaacjensen** [comment]
We run xmlsec 2.1.6 with this patch locally.

**Comment by seanjmullan** [comment]
For other system properties, we typically prefix them with the package hierarchy to avoid name clashes, so I would recommend:

`org.apache.xml.security.securerandom.algorithm`

Otherwise, this fix looks ok to me, but I think @coheigea should give the approval since this is in the stax implementation.

On a related issue though, I think we should not hard-code "SHA1PRNG" as the default. There are better alternatives in the JDK now. I would replace this with a call to `new SecureRandom()` or possibly `SecureRandom.getInstanceStrong()`. I haven't looked at the usage to see which is more appropriate.

**Comment by isaacjensen** [comment]
Thanks for the comments @seanjmullan. Let's see if we can get @coheigea approval on this.

**Review by coheigea — COMMENTED** [review]
The 2.1.x-fixes branch isn't active any more, can you submit a PR against master please?

**Comment by isaacjensen** [comment]
@coheigea PR opened against master!

**Pull request closed without merging**
